---
- hosts: localhost
  connection: local
  tasks:
    - name: create resource group
      azure_rm_resourcegroup:
        name: playground
        location: westeurope
      register: rg
    - name: create storage account
      azure_rm_storageaccount:
        resource_group: playground
        name: starterappstorage
        type: Standard_LRS
    - name: create function app
      azure_rm_functionapp:
        resource_group: playground
        storage_account: starterappstorage
        name: starterfunctionapp
        app_settings:
          FUNCTIONS_WORKER_RUNTIME: dotnet
    - name: deploy function
      script: deploy.sh
    - debug:
        var: rg 