---
- hosts: localhost
  connection: local
  vars_files:
    - "group_vars/{{ lookup('env', 'TARGET_ENV') }}.yml"

  pre_tasks:
    - name: create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
      register: rg
    - debug:
        var: rg
  
  roles:
    - webapp
    - function
  
  