---
- hosts: localhost
  connection: local
  vars_files:
    - "group_vars/{{ lookup('env', 'TARGET_ENV') }}.yml"

  tasks:
    - name: create resource group
      azure_rm_resourcegroup:
        name: "{{ functions.resource_group }}"
        location: "{{ functions.location }}"
      register: rg
    - name: create storage account
      azure_rm_storageaccount:
        resource_group: "{{ functions.resource_group }}"
        name: "{{ functions.storage_account }}"
        type: Standard_LRS
    - name: create function app
      azure_rm_functionapp:
        resource_group: "{{ functions.resource_group }}"
        storage_account: "{{ functions.storage_account }}"
        name: "{{ functions.app_name }}"
        app_settings:
          FUNCTIONS_WORKER_RUNTIME: dotnet
    - name: deploy function app
      script: deploy.sh
      environment:
        ARTEFACT: "Kalibrate.Pricing.Functions"
        RESOURCE_GROUP: "{{ functions.resource_group }}"
        APP_NAME: "{{ functions.app_name }} "
      tags:
        - deploy
    - debug:
        var: rg