---
  - name: create storage account
    azure_rm_storageaccount:
      resource_group: "{{ resource_group }}"
      name: "{{ functions.storage_account }}"
      type: Standard_LRS
  
  - name: retrieve storage access key
    shell: az storage account keys list --account-name {{ functions.storage_account }} --resource-group {{ resource_group }} --query "[0].value" --output tsv
    register: storage_access_key  
  - debug:
        msg: "{{ storage_access_key }}"  
  
  - name: create function app
    azure_rm_functionapp:
      resource_group: "{{ resource_group }}"
      storage_account: "{{ functions.storage_account }}"
      name: "{{ functions.app_name }}"
      app_settings:
        FUNCTIONS_WORKER_RUNTIME:  dotnet
  
  - name: deploy function app
    script: deploy.sh
    environment:
      ARTEFACT: "Kalibrate.Pricing.Functions" 
      RESOURCE_GROUP: "{{ resource_group }}"
      APP_NAME: "{{ functions.app_name }} "
    register: deploy
    tags:
      - deploy
  - debug:
      msg: "{{ deploy }}"