---
  - name: create service bus namespace
    shell: . ./neel.sh && sb_createnamespace {{ servicebus.namespace }} {{ resource_group }}

  - name: get service bus connection string
    shell: . ./neel.sh && sb_getauthrule_constring {{ servicebus.namespace }} {{ resource_group }} RootManageSharedAccessKey
    register: cmd_output
  - set_fact:
      sb_connection_string: "{{ cmd_output.stdout }}"